"""
analysis_pm_robotics.py
======================

This script analyses the synthetic project management dataset generated by
`generate_pm_dataset.py`. It addresses several key business questions relevant to
Project Managers overseeing GreyOrange warehouse automation deployments:

1. **Impact of project complexity on schedule and cost variance**
   - Examine how the size of the warehouse and number of robots influence deviations
     from estimated duration and cost.
2. **Effect of robot mix (HTM vs. VTM)**
   - Determine whether the proportion of vertical to horizontal tote movers affects
     schedule variance, cost variance and commissioning time.
3. **Tool utilisation and project outcomes**
   - Analyse whether using project planning tools (VOS, CAD, Tower) correlates with
     shorter commissioning periods and reduced variances.
4. **Risk category influence**
   - Compare projects across Low, Medium and High risk categories to assess
     performance differences.
5. **Regional performance differences**
   - Investigate whether projects in specific regions tend to perform better in terms
     of duration, cost or commissioning time.

The analysis results are printed to the console. Optionally, summary plots are
generated and saved to a `figures` directory.

Example usage:
```
python analysis_pm_robotics.py --input pm_project_dataset.csv --show_plots
```
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


def load_dataset(csv_path: Path) -> pd.DataFrame:
    """Load dataset from a CSV file."""
    df = pd.read_csv(csv_path)
    return df


def analyse_complexity(df: pd.DataFrame) -> None:
    """Analyse impact of complexity on schedule and cost variance."""
    print("\n=== Question 1: Impact of project complexity ===")
    # Group by complexity category and compute summary statistics
    summary = (
        df.groupby("complexity_category")[
            ["schedule_variance_days", "cost_variance_kusd", "commissioning_days"]
        ]
        .agg(["mean", "median", "std"])
        .round(2)
    )
    print("\nSchedule and cost variance by complexity category:")
    print(summary)

    # Linear regression of schedule variance vs. warehouse size and total robots
    X = df[["warehouse_size_sqft", "total_robots"]]
    y_sched = df["schedule_variance_days"]
    y_cost = df["cost_variance_kusd"]
    # Normalise features for interpretability
    X_norm = (X - X.mean()) / X.std()
    lm_sched = LinearRegression().fit(X_norm, y_sched)
    lm_cost = LinearRegression().fit(X_norm, y_cost)
    print("\nLinear regression results (coefficients are standardised):")
    print("Schedule variance ~ warehouse_size_sqft + total_robots")
    print(
        f"Coefficients: warehouse_size={lm_sched.coef_[0]:.2f}, total_robots={lm_sched.coef_[1]:.2f}, intercept={lm_sched.intercept_:.2f}"
    )
    print(f"R^2: {r2_score(y_sched, lm_sched.predict(X_norm)):.3f}")
    print("Cost variance ~ warehouse_size_sqft + total_robots")
    print(
        f"Coefficients: warehouse_size={lm_cost.coef_[0]:.2f}, total_robots={lm_cost.coef_[1]:.2f}, intercept={lm_cost.intercept_:.2f}"
    )
    print(f"R^2: {r2_score(y_cost, lm_cost.predict(X_norm)):.3f}")


def analyse_robot_mix(df: pd.DataFrame) -> None:
    """Analyse effect of robot mix (HTM vs. VTM)."""
    print("\n=== Question 2: Effect of robot mix (HTM vs. VTM) ===")
    # Compute VTM proportion
    df = df.copy()
    df["vtm_proportion"] = df["num_vtm"] / df["total_robots"]
    # Bin into low, medium, high groups
    df["vtm_mix_category"] = pd.cut(
        df["vtm_proportion"],
        bins=[-np.inf, 0.33, 0.66, np.inf],
        labels=["Low VTM", "Medium VTM", "High VTM"],
    )
    summary = (
        df.groupby("vtm_mix_category")[
            ["schedule_variance_days", "cost_variance_kusd", "commissioning_days"]
        ]
        .mean()
        .round(2)
    )
    print("\nAverage variance and commissioning days by VTM mix category:")
    print(summary)


def analyse_tool_usage(df: pd.DataFrame) -> None:
    """Analyse tool utilisation and project outcomes."""
    print("\n=== Question 3: Tool utilisation and project outcomes ===")
    tools = ["uses_vos", "uses_cad", "uses_tower"]
    for tool in tools:
        summary = df.groupby(tool)[
            ["schedule_variance_days", "cost_variance_kusd", "commissioning_days"]
        ].mean().round(2)
        print(f"\nImpact of {tool}:")
        print(summary)


def analyse_risk(df: pd.DataFrame) -> None:
    """Compare outcomes by risk category."""
    print("\n=== Question 4: Risk category influence ===")
    summary = (
        df.groupby("risk_category")[
            ["schedule_variance_days", "cost_variance_kusd", "commissioning_days"]
        ]
        .agg(["mean", "median"])
        .round(2)
    )
    print(summary)


def analyse_region(df: pd.DataFrame) -> None:
    """Analyse regional performance differences."""
    print("\n=== Question 5: Regional performance differences ===")
    summary = (
        df.groupby("region")[
            ["estimated_duration_days", "actual_duration_days", "estimated_cost_kusd", "actual_cost_kusd", "commissioning_days"]
        ]
        .mean()
        .round(2)
    )
    print(summary)


def create_plots(df: pd.DataFrame, out_dir: Path) -> None:
    """Generate diagnostic plots and save them to the output directory."""
    out_dir.mkdir(parents=True, exist_ok=True)
    sns.set(style="whitegrid")

    # Scatter of schedule variance vs. complexity
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.scatterplot(
        data=df,
        x="total_robots",
        y="schedule_variance_days",
        hue="complexity_category",
        palette="viridis",
        ax=ax,
    )
    ax.set_title("Schedule variance vs. number of robots")
    fig.tight_layout()
    fig.savefig(out_dir / "schedule_variance_vs_robots.png")
    plt.close(fig)

    # Boxplots of commissioning days by tool usage
    for tool in ["uses_vos", "uses_cad", "uses_tower"]:
        fig, ax = plt.subplots(figsize=(6, 4))
        sns.boxplot(x=df[tool], y=df["commissioning_days"], ax=ax)
        ax.set_title(f"Commissioning days by {tool}")
        ax.set_xlabel(tool)
        fig.tight_layout()
        fig.savefig(out_dir / f"commissioning_by_{tool}.png")
        plt.close(fig)


def main():
    parser = argparse.ArgumentParser(
        description="Analyse synthetic GreyOrange PM project dataset"
    )
    parser.add_argument(
        "--input",
        type=str,
        default="pm_project_dataset.csv",
        help="Input dataset CSV file (default: pm_project_dataset.csv)",
    )
    parser.add_argument(
        "--show_plots",
        action="store_true",
        help="If set, generate and save diagnostic plots to a 'figures' directory",
    )
    args = parser.parse_args()

    df = load_dataset(Path(args.input))
    analyse_complexity(df)
    analyse_robot_mix(df)
    analyse_tool_usage(df)
    analyse_risk(df)
    analyse_region(df)

    if args.show_plots:
        out_dir = Path("figures")
        create_plots(df, out_dir)
        print(f"\nPlots have been saved to {out_dir}.")


if __name__ == "__main__":
    main()